repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-toml
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: name-tests-test
    -   id: pretty-format-json
    -   id: sort-simple-yaml
    -   id: trailing-whitespace
-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.12.0
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
    -   id: add-trailing-comma
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.292
    hooks:
    -   id: ruff
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.0
    hooks:
    -   id: mypy
