[tool.poetry]
name = "cyclic-toposort"
version = "1.1.0"
description = "A sorting algorithm for directed cyclic graphs that results in a sorting with minimal cyclic edges."
authors = ["Paul Pauls <mail@paulpauls.de>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
